### ISSUE TITLE
Not enough balance with balance and trying to send - message makes no sense

### ISSUE THREAD

**Issue by bioduds** [bitfinexcom/smidgen#22]
I'm testing multisig wallet, I'm trying to send iotas. It gives me a totally wrong message, not related, saying I have no balance whence I do. Print attached.
![screenshot_20170918_203853](https://user-images.githubusercontent.com/2072730/30569449-625ce81c-9cb1-11e7-98de-80378a47f0f1.png)

**Comment by robertkowalski** [comment]
hi @bioduds,

thanks for the report!

How much balance do you have on your multisig wallet? You can check the balance with

```
smidgen get-balance $your-multisig-address
```

it can happen that a transfer wasn't confirmed from the network yet and hasn't appeared in your multisig wallet yet. 

In fact this error comes directly from the iota lib, which checks the balance of an address before a transfer.

**Comment by bioduds** [comment]
I'm testing. I have 10 iotas on one and 5 on another.

**Comment by robertkowalski** [comment]
ok! 

if it wasn't confirmed yet try reattaching every 30mins, thats whats currently recommended to speed up transfers.

**Comment by bioduds** [comment]
Actually, it is not processing

**Comment by robertkowalski** [comment]
@bioduds in the future we have better error messages:

![screen shot 2017-09-20 at 10 58 38](https://user-images.githubusercontent.com/298166/30635615-42fc6932-9df3-11e7-883f-f2342c277d6c.png)

thanks for your input so far! I think we can close this issue now?

**Comment by robertkowalski** [comment]
closing: abandoned issue
