### ISSUE TITLE
Unexpected token when create wallet

### ISSUE THREAD

**Issue by yillkid** [bitfinexcom/smidgen#25]
$ smidgen multisig create bob multisig.txt

ERR! Unexpected token = 
ERR! SyntaxError: Unexpected token =
ERR!     at exports.runInThisContext (vm.js:53:16)
ERR!     at Module._compile (module.js:374:25)
ERR!     at Object.Module._extensions..js (module.js:417:10)
ERR!     at Module.load (module.js:344:32)
ERR!     at Function.Module._load (module.js:301:12)
ERR!     at Module.require (module.js:354:17)
ERR!     at require (internal/module.js:12:17)
ERR!     at /usr/local/lib/node_modules/smidgen/lib/smidgen.js:76:17
ERR!     at Array.forEach (native)
ERR!     at populateCommands (/usr/local/lib/node_modules/smidgen/lib/smidgen.js:74:6)
ERR! 
ERR! 
ERR! smidgen: 1.0.0 node: v4.2.6
ERR! please open an issue including this log on https://github.com/bitfinexcom/smidgen/issues

**Comment by robertkowalski** [comment]
please update to latest node (8.x)

**Comment by robertkowalski** [comment]
was a little bit in a hurry. so the node version you are using is too old. it doesn't support the ES6 features we use in smidgen. please upgrade to latest LTS (node 8). it will sovle the problem.

thanks for reporting and enjoy smidgen!
