### ISSUE TITLE
Creating Multisignature Wallet

### ISSUE THREAD

**Issue by swdevMPaul** [bitfinexcom/smidgen#35]
Hello.

Thank you for your good work in creating smidgen. 

1)
I have installed it and generated seed:

C:\Users\User\Downloads\smidgen-master\smidgen-master>smidgen generate-seed
PRAWETVIZYPK9HMLUOOFRMPBRFFJPEMFWIKSMZ9TDRBOLIE9LUOBZTMTE9V9YIV9TWAZSFFGITQXZURHM

2) Now with this seed when I run:

C:\Users\User\Downloads\smidgen-master\smidgen-master>smidgen multisig create pavel multisig.txt
Enter your seed:
ERR! no seed set
ERR! Error: no seed set
ERR!     at createWallet (C:\Users\User\AppData\Roaming\npm\node_modules\smidgen\lib\cmds\multisig.js:583:24)
ERR!     at finalize (C:\Users\User\AppData\Roaming\npm\node_modules\smidgen\lib\cmds\multisig.js:666:5)
ERR!     at getSeed (C:\Users\User\AppData\Roaming\npm\node_modules\smidgen\lib\cmds\multisig.js:661:7)
ERR!     at read (C:\Users\User\AppData\Roaming\npm\node_modules\smidgen\lib\get-seed.js:16:5)
ERR!     at Interface.onLine (C:\Users\User\AppData\Roaming\npm\node_modules\smidgen\node_modules\read\lib\read.js:111:5)
ERR!     at Interface.emit (events.js:159:13)
ERR!     at Interface._onLine (readline.js:287:10)
ERR!     at Interface._line (readline.js:642:8)
ERR!     at Interface._ttyWrite (readline.js:922:14)
ERR!     at ReadStream.onkeypress (readline.js:165:10)
ERR!
ERR!
ERR! smidgen: 1.2.0 - iota.lib.js: 0.4.5 - node: v9.3.0
ERR! please open an issue including this log on https://github.com/bitfinexcom/smidgen/issues

Please help why I get such error ? I need to create this multi-signature wallet.

With hope to solve,

Pavel.

**Comment by robertkowalski** [comment]
@swdevMPaul did you copy the generated seed and then pasted it into the terminal before hitting enter? `ERR! no seed set` appears when you just hit enter without copy / pasting your seed into the terminal

**Comment by robertkowalski** [comment]
@swdevMPaul i added some validation and a better error message in https://github.com/robertkowalski/smidgen/commit/1bbe41545f0be3bebdcaae1ea889a4940c536e97
