### ISSUE TITLE
Restore wallet with multisig addresses

### ISSUE THREAD

**Issue by joshirio** [bitfinexcom/smidgen#40]
First, let me say how great this tool is and thank you for creating it. It's the only multisig tool for IOTA right now that actually works. I'm planning to use smidgen as the backend to create a simple cold wallet GUI based on multisig where one of the two parties signs the transaction on an offline computer. This simple wallet could eventually become also a simple multisig GUI in addition to the cold signing workflow.

Now, the real issue, as far as I understand, there's currently no command to restore multisig addresses, which were potentially used previously. After a snapshot or if the user loses the file (state of the multisig), restoring the multisig wallet with the seeds by using `multisig create`, creates only the first multisig address (main address) without checking further key indexes.

What would be a way to populate the file with the latest non used multisig address?
If there's none (currently), is it possible to implement a command to generate/add multisig addresses to the file?

I understand this is beta, but I hope there will be an address restore feature in the future.

**Comment by robertkowalski** [comment]
i just added `smidgen multisig reattach`
